import React from 'react';
import { ArrowLeft, Download, CheckCircle2, AlertTriangle } from 'lucide-react';
import { Badge } from './ui/badge';

interface SubmissionReportPDFProps {
  onBack: () => void;
  candidateName?: string;
}

export function SubmissionReportPDF({ onBack, candidateName = 'Marcus Chen' }: SubmissionReportPDFProps) {
  return (
    <div className="flex flex-col h-full bg-slate-100">
      {/* Top Control Bar */}
      <div className="px-8 py-4 border-b border-slate-200 bg-white shrink-0">
        <div className="max-w-[1200px] mx-auto flex items-center justify-between">
          <button
            onClick={onBack}
            className="flex items-center gap-2 text-slate-500 hover:text-slate-900 transition-colors text-sm font-medium group"
          >
            <ArrowLeft className="w-4 h-4 transition-transform group-hover:-translate-x-0.5" />
            Back to Report
          </button>
          <button className="px-5 py-2.5 bg-[#002A54] text-white rounded-lg text-[13px] font-bold hover:bg-[#003A70] transition-all flex items-center gap-2 shadow-sm">
            <Download className="w-4 h-4" /> Export PDF
          </button>
        </div>
      </div>

      {/* PDF Document Area */}
      <div className="flex-1 overflow-y-auto py-10 px-8">
        <div className="max-w-[210mm] mx-auto space-y-8">
          {/* Page 1 */}
          <div className="bg-white shadow-lg" style={{ minHeight: '297mm', padding: '28mm 20mm' }}>
            {/* Document Header */}
            <div className="mb-10 pb-8 border-b-2 border-slate-200">
              <h1 className="text-3xl font-black text-[#002A54] mb-3 tracking-tight">
                Submission Intelligence Report
              </h1>
              <div className="flex items-start justify-between mb-4">
                <div>
                  <p className="text-lg font-bold text-slate-900 mb-1">{candidateName}</p>
                  <p className="text-sm text-slate-600 font-medium">Role: SAP TM Functional Consultant</p>
                  <p className="text-xs text-slate-400 mt-1">February 24, 2026</p>
                </div>
                <div className="text-right">
                  <p className="text-[10px] text-slate-400 font-medium mb-2">Generated by DeepSAP</p>
                  <div className="flex flex-wrap gap-2 justify-end">
                    <Badge className="bg-emerald-50 text-emerald-700 border-emerald-200 px-2 py-0.5 text-[9px] font-black">
                      Submission-safe
                    </Badge>
                    <Badge className="bg-blue-50 text-blue-700 border-blue-200 px-2 py-0.5 text-[9px] font-black">
                      Risk-checked
                    </Badge>
                    <Badge className="bg-slate-50 text-slate-700 border-slate-200 px-2 py-0.5 text-[9px] font-black">
                      Client-ready
                    </Badge>
                  </div>
                </div>
              </div>
            </div>

            {/* Submission Verdict */}
            <div className="mb-10">
              <h2 className="text-xl font-black text-[#002A54] mb-4 tracking-tight uppercase">
                Submission Verdict
              </h2>
              <div className="flex items-center gap-8 mb-6 p-6 bg-slate-50 rounded-2xl border border-slate-200">
                <div>
                  <div className="text-5xl font-black text-[#B7410E] leading-none mb-2">84%</div>
                  <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest">
                    Submission Readiness
                  </div>
                </div>
                <div className="flex-1 space-y-2">
                  <div className="flex items-center gap-3">
                    <span className="text-xs font-bold text-slate-500 w-32">Verdict:</span>
                    <Badge className="bg-emerald-50 text-emerald-700 border-emerald-200 px-3 py-1 text-xs font-bold">
                      Strong Submit
                    </Badge>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-xs font-bold text-slate-500 w-32">Confidence:</span>
                    <Badge className="bg-blue-50 text-blue-700 border-blue-200 px-3 py-1 text-xs font-bold">
                      High
                    </Badge>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-xs font-bold text-slate-500 w-32">Risk Posture:</span>
                    <Badge className="bg-amber-50 text-amber-700 border-amber-200 px-3 py-1 text-xs font-bold">
                      Medium-Low
                    </Badge>
                  </div>
                </div>
              </div>
              <p className="text-sm text-slate-700 leading-relaxed font-medium mb-1">
                This candidate is a strong submission for the current SAP TM functional requirement based on direct JD
                alignment, validated delivery evidence, and scenario-level technical reasoning. The profile is
                submission-ready for staffing use with clear strengths in TM functional scope, integration-aware
                execution, and stakeholder-facing delivery behavior. Watch areas are identified transparently and can
                be addressed with targeted validation if needed.
              </p>
            </div>

            {/* Client Fit Summary */}
            <div className="mb-10">
              <h2 className="text-xl font-black text-[#002A54] mb-4 tracking-tight uppercase">Client Fit Summary</h2>
              <div className="grid grid-cols-1 gap-3">
                <div className="flex items-center justify-between p-4 bg-slate-50 rounded-xl border border-slate-100">
                  <span className="text-xs font-bold text-slate-700">Role-critical fit</span>
                  <Badge className="bg-emerald-50 text-emerald-700 border-emerald-200 text-[9px] font-black px-2 py-0.5">
                    Strong
                  </Badge>
                </div>
                <div className="flex items-center justify-between p-4 bg-slate-50 rounded-xl border border-slate-100">
                  <span className="text-xs font-bold text-slate-700">Integration readiness</span>
                  <Badge className="bg-emerald-50 text-emerald-700 border-emerald-200 text-[9px] font-black px-2 py-0.5">
                    Strong
                  </Badge>
                </div>
                <div className="flex items-center justify-between p-4 bg-slate-50 rounded-xl border border-slate-100">
                  <span className="text-xs font-bold text-slate-700">Lifecycle coverage</span>
                  <Badge className="bg-blue-50 text-blue-700 border-blue-200 text-[9px] font-black px-2 py-0.5">
                    Moderate
                  </Badge>
                </div>
                <div className="flex items-center justify-between p-4 bg-slate-50 rounded-xl border border-slate-100">
                  <span className="text-xs font-bold text-slate-700">Client-facing readiness</span>
                  <Badge className="bg-emerald-50 text-emerald-700 border-emerald-200 text-[9px] font-black px-2 py-0.5">
                    Strong
                  </Badge>
                </div>
                <div className="flex items-center justify-between p-4 bg-slate-50 rounded-xl border border-slate-100">
                  <span className="text-xs font-bold text-slate-700">Submission risk level</span>
                  <Badge className="bg-amber-50 text-amber-700 border-amber-200 text-[9px] font-black px-2 py-0.5">
                    Medium-Low
                  </Badge>
                </div>
              </div>
            </div>

            {/* JD Alignment Snapshot */}
            <div className="mb-10">
              <h2 className="text-xl font-black text-[#002A54] mb-4 tracking-tight uppercase">
                JD Alignment Snapshot
              </h2>
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="border-b-2 border-slate-300">
                      <th className="pb-3 pr-3 text-[10px] font-black text-slate-500 uppercase tracking-wider">
                        JD Requirement
                      </th>
                      <th className="pb-3 px-3 text-[10px] font-black text-slate-500 uppercase tracking-wider">
                        Match
                      </th>
                      <th className="pb-3 px-3 text-[10px] font-black text-slate-500 uppercase tracking-wider">
                        Evidence Source
                      </th>
                      <th className="pb-3 pl-3 text-[10px] font-black text-slate-500 uppercase tracking-wider">
                        Submission Framing
                      </th>
                    </tr>
                  </thead>
                  <tbody className="text-xs">
                    <tr className="border-b border-slate-200">
                      <td className="py-3 pr-3 font-bold text-slate-700">SAP TM functional configuration</td>
                      <td className="py-3 px-3">
                        <Badge className="bg-emerald-50 text-emerald-700 border-emerald-200 text-[8px] font-black px-1.5 py-0.5">
                          Strong
                        </Badge>
                      </td>
                      <td className="py-3 px-3 text-slate-600">Resume + Technical</td>
                      <td className="py-3 pl-3 text-slate-600 font-medium">Lead with this</td>
                    </tr>
                    <tr className="border-b border-slate-200">
                      <td className="py-3 pr-3 font-bold text-slate-700">S/4HANA exposure</td>
                      <td className="py-3 px-3">
                        <Badge className="bg-emerald-50 text-emerald-700 border-emerald-200 text-[8px] font-black px-1.5 py-0.5">
                          Strong
                        </Badge>
                      </td>
                      <td className="py-3 px-3 text-slate-600">Resume + Validation</td>
                      <td className="py-3 pl-3 text-slate-600 font-medium">Include in top summary</td>
                    </tr>
                    <tr className="border-b border-slate-200">
                      <td className="py-3 pr-3 font-bold text-slate-700">TM integration experience</td>
                      <td className="py-3 px-3">
                        <Badge className="bg-emerald-50 text-emerald-700 border-emerald-200 text-[8px] font-black px-1.5 py-0.5">
                          Strong
                        </Badge>
                      </td>
                      <td className="py-3 px-3 text-slate-600">Technical + Resume</td>
                      <td className="py-3 pl-3 text-slate-600 font-medium">Highlight with examples</td>
                    </tr>
                    <tr className="border-b border-slate-200">
                      <td className="py-3 pr-3 font-bold text-slate-700">Go-live and hypercare ownership</td>
                      <td className="py-3 px-3">
                        <Badge className="bg-blue-50 text-blue-700 border-blue-200 text-[8px] font-black px-1.5 py-0.5">
                          Moderate
                        </Badge>
                      </td>
                      <td className="py-3 px-3 text-slate-600">Resume + Panel</td>
                      <td className="py-3 pl-3 text-slate-600 font-medium">Frame honestly, validate if needed</td>
                    </tr>
                    <tr>
                      <td className="py-3 pr-3 font-bold text-slate-700">Advanced optimization depth</td>
                      <td className="py-3 px-3">
                        <Badge className="bg-blue-50 text-blue-700 border-blue-200 text-[8px] font-black px-1.5 py-0.5">
                          Moderate
                        </Badge>
                      </td>
                      <td className="py-3 px-3 text-slate-600">Technical validation</td>
                      <td className="py-3 pl-3 text-slate-600 font-medium">Do not over-position</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            {/* Scenario Readiness */}
            <div className="mb-10">
              <h2 className="text-xl font-black text-[#002A54] mb-4 tracking-tight uppercase">Scenario Readiness</h2>
              <div className="flex items-center gap-8 mb-4 p-6 bg-slate-50 rounded-2xl border border-slate-200">
                <div>
                  <div className="text-4xl font-black text-[#B7410E] leading-none mb-2">84</div>
                  <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest">
                    Scenario Score
                  </div>
                </div>
                <div className="flex-1">
                  <Badge className="bg-emerald-50 text-emerald-700 border-emerald-200 px-2 py-1 text-xs font-bold mb-2">
                    High
                  </Badge>
                  <p className="text-xs text-slate-600 font-medium">
                    Scenario Type: TM Go-Live + Integration-heavy Delivery
                  </p>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="flex items-center justify-between p-3 bg-white rounded-xl border border-slate-200">
                  <span className="text-xs font-bold text-slate-600">Functional scenario handling</span>
                  <Badge className="bg-emerald-50 text-emerald-700 border-emerald-200 text-[8px] font-black px-1.5 py-0.5">
                    Strong
                  </Badge>
                </div>
                <div className="flex items-center justify-between p-3 bg-white rounded-xl border border-slate-200">
                  <span className="text-xs font-bold text-slate-600">Integration incident triage</span>
                  <Badge className="bg-emerald-50 text-emerald-700 border-emerald-200 text-[8px] font-black px-1.5 py-0.5">
                    Strong
                  </Badge>
                </div>
                <div className="flex items-center justify-between p-3 bg-white rounded-xl border border-slate-200">
                  <span className="text-xs font-bold text-slate-600">Cutover discipline</span>
                  <Badge className="bg-blue-50 text-blue-700 border-blue-200 text-[8px] font-black px-1.5 py-0.5">
                    Moderate
                  </Badge>
                </div>
                <div className="flex items-center justify-between p-3 bg-white rounded-xl border border-slate-200">
                  <span className="text-xs font-bold text-slate-600">Hypercare stabilization</span>
                  <Badge className="bg-blue-50 text-blue-700 border-blue-200 text-[8px] font-black px-1.5 py-0.5">
                    Moderate
                  </Badge>
                </div>
              </div>
            </div>

            {/* Footer */}
            <div className="mt-12 pt-6 border-t border-slate-200 flex items-center justify-between">
              <p className="text-[10px] text-slate-400 font-medium">
                Generated by DeepSAP Submission Intelligence
              </p>
              <p className="text-[10px] text-slate-400 font-bold">Page 1 of 2</p>
            </div>
          </div>

          {/* Page 2 */}
          <div className="bg-white shadow-lg" style={{ minHeight: '297mm', padding: '28mm 20mm' }}>
            {/* Submission Risk Check */}
            <div className="mb-10">
              <h2 className="text-xl font-black text-[#002A54] mb-4 tracking-tight uppercase">
                Submission Risk Check
              </h2>
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse mb-4">
                  <thead>
                    <tr className="border-b-2 border-slate-300">
                      <th className="pb-3 pr-3 text-[10px] font-black text-slate-500 uppercase tracking-wider">
                        Risk
                      </th>
                      <th className="pb-3 px-3 text-[10px] font-black text-slate-500 uppercase tracking-wider">
                        Severity
                      </th>
                      <th className="pb-3 pl-3 text-[10px] font-black text-slate-500 uppercase tracking-wider">
                        Mitigation
                      </th>
                    </tr>
                  </thead>
                  <tbody className="text-xs">
                    <tr className="border-b border-slate-200">
                      <td className="py-3 pr-3 font-bold text-slate-700">
                        Advanced optimization depth not deeply evidenced
                      </td>
                      <td className="py-3 px-3">
                        <Badge className="bg-amber-50 text-amber-700 border-amber-200 text-[8px] font-black px-1.5 py-0.5">
                          Moderate
                        </Badge>
                      </td>
                      <td className="py-3 pl-3 text-slate-600">Position as core-fit strong, not optimization specialist</td>
                    </tr>
                    <tr className="border-b border-slate-200">
                      <td className="py-3 pr-3 font-bold text-slate-700">Go-live and hypercare depth moderate</td>
                      <td className="py-3 px-3">
                        <Badge className="bg-amber-50 text-amber-700 border-amber-200 text-[8px] font-black px-1.5 py-0.5">
                          Moderate
                        </Badge>
                      </td>
                      <td className="py-3 pl-3 text-slate-600">Add one clarification note or prompt</td>
                    </tr>
                    <tr>
                      <td className="py-3 pr-3 font-bold text-slate-700">
                        Middleware build ownership not proven (if required)
                      </td>
                      <td className="py-3 px-3">
                        <Badge className="bg-blue-50 text-blue-700 border-blue-200 text-[8px] font-black px-1.5 py-0.5">
                          Conditional
                        </Badge>
                      </td>
                      <td className="py-3 pl-3 text-slate-600">
                        State troubleshooting exposure vs build ownership clearly
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            {/* Recommended Positioning */}
            <div className="mb-10">
              <h2 className="text-xl font-black text-[#002A54] mb-4 tracking-tight uppercase">
                Recommended Positioning
              </h2>
              <p className="text-sm text-slate-700 leading-relaxed font-medium mb-6">
                This candidate is best positioned as a strong SAP TM functional delivery consultant with validated
                integration-aware execution, reliable delivery behavior, and client-ready communication. Best fit is
                for implementation and support environments where functional depth and structured triage matter more
                than deep optimization specialization.
              </p>
              <div className="grid grid-cols-2 gap-6">
                <div className="p-5 bg-emerald-50/30 rounded-xl border border-emerald-100">
                  <h3 className="text-xs font-black text-emerald-700 uppercase tracking-widest mb-3">Do say</h3>
                  <ul className="space-y-2">
                    <li className="flex items-start gap-2">
                      <CheckCircle2 className="w-3 h-3 text-emerald-600 shrink-0 mt-0.5" />
                      <span className="text-[11px] text-slate-700 font-medium">
                        Validated against JD and delivery signals
                      </span>
                    </li>
                    <li className="flex items-start gap-2">
                      <CheckCircle2 className="w-3 h-3 text-emerald-600 shrink-0 mt-0.5" />
                      <span className="text-[11px] text-slate-700 font-medium">
                        Strong core-fit with clear evidence
                      </span>
                    </li>
                    <li className="flex items-start gap-2">
                      <CheckCircle2 className="w-3 h-3 text-emerald-600 shrink-0 mt-0.5" />
                      <span className="text-[11px] text-slate-700 font-medium">
                        Submission-safe with known watch areas
                      </span>
                    </li>
                  </ul>
                </div>

                <div className="p-5 bg-rose-50/30 rounded-xl border border-rose-100">
                  <h3 className="text-xs font-black text-rose-700 uppercase tracking-widest mb-3">Do not say</h3>
                  <ul className="space-y-2">
                    <li className="flex items-start gap-2">
                      <AlertTriangle className="w-3 h-3 text-rose-600 shrink-0 mt-0.5" />
                      <span className="text-[11px] text-slate-700 font-medium">
                        Deep optimization expert, unless validated
                      </span>
                    </li>
                    <li className="flex items-start gap-2">
                      <AlertTriangle className="w-3 h-3 text-rose-600 shrink-0 mt-0.5" />
                      <span className="text-[11px] text-slate-700 font-medium">
                        End-to-end middleware build owner, unless proven
                      </span>
                    </li>
                    <li className="flex items-start gap-2">
                      <AlertTriangle className="w-3 h-3 text-rose-600 shrink-0 mt-0.5" />
                      <span className="text-[11px] text-slate-700 font-medium">
                        Go-live lead, unless directly evidenced
                      </span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>

            {/* Client Summary */}
            <div className="mb-10">
              <h2 className="text-xl font-black text-[#002A54] mb-4 tracking-tight uppercase">Client Summary</h2>
              <div className="space-y-4">
                <div className="p-5 bg-slate-50 rounded-xl border border-slate-100">
                  <h3 className="text-xs font-black text-slate-600 uppercase tracking-widest mb-2">Short Version</h3>
                  <p className="text-sm text-slate-700 leading-relaxed font-medium">
                    Strong SAP TM functional submission aligned to JD core scope with validated delivery-fit across
                    technical reasoning, integration-aware execution, and stakeholder readiness. Recommended for
                    role-critical execution needs. Watch areas are clearly identified and manageable.
                  </p>
                </div>

                <div className="p-5 bg-slate-50 rounded-xl border border-slate-100">
                  <h3 className="text-xs font-black text-slate-600 uppercase tracking-widest mb-2">
                    Detailed Version
                  </h3>
                  <p className="text-sm text-slate-700 leading-relaxed font-medium">
                    This profile aligns well to the JD for SAP TM functional delivery and is supported by multi-source
                    validation. Core strengths include TM functional capability, integration triage logic, and
                    client-facing execution behavior. Moderate watch areas exist in advanced optimization depth and
                    go-live stabilization ownership, which can be validated with targeted prompts if required by the
                    client program.
                  </p>
                </div>
              </div>
            </div>

            {/* Suggested Validation Prompts */}
            <div className="mb-10">
              <h2 className="text-xl font-black text-[#002A54] mb-4 tracking-tight uppercase">
                Suggested Validation Prompts
              </h2>
              <ul className="space-y-3">
                <li className="flex items-start gap-3 p-4 bg-blue-50/30 rounded-xl border border-blue-100">
                  <span className="text-[#B7410E] font-black text-sm mt-0.5">1.</span>
                  <span className="text-xs text-slate-700 font-medium leading-relaxed">
                    Walk through a TM go-live stabilization issue you handled and the controls you used
                  </span>
                </li>
                <li className="flex items-start gap-3 p-4 bg-blue-50/30 rounded-xl border border-blue-100">
                  <span className="text-[#B7410E] font-black text-sm mt-0.5">2.</span>
                  <span className="text-xs text-slate-700 font-medium leading-relaxed">
                    Describe an integration incident between TM and EWM and your triage steps
                  </span>
                </li>
              </ul>
            </div>

            {/* Footer */}
            <div className="mt-12 pt-6 border-t border-slate-200">
              <div className="flex items-center justify-between mb-2">
                <p className="text-[10px] text-slate-400 font-medium">
                  Generated by DeepSAP Submission Intelligence
                </p>
                <p className="text-[10px] text-slate-400 font-bold">Page 2 of 2</p>
              </div>
              <p className="text-[9px] text-slate-400 italic">Evidence-based submission support summary</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
